bold:
    name: profiles_buttons_bold
    key: B
    className: bold
    closeWith:
        textile: "*"
    openWith:
        textile: "*"

code:
    name: profiles_buttons_code
    className: code
    closeWith:
        textile: "@"
    openWith:
        textile: "@"

clips:
    name: profiles_buttons_clips
    className: clips

deleted:
    name: profiles_buttons_deleted
    key: S
    className: deleted
    closeWith:
        textile: "-"
    openWith:
        textile: "-"

formatting:
    name: profiles_buttons_formatting
    className: formatting
    children:
        h1:
            name: profiles_buttons_formatting_option_h1
            openWith:
                textile: "h1. "
        h2:
            name: profiles_buttons_formatting_option_h2
            openWith:
                textile: "h2. "
        h3:
            name: profiles_buttons_formatting_option_h3
            openWith:
                textile: "h3. "
        h4:
            name: profiles_buttons_formatting_option_h4
            openWith:
                textile: "h4. "
        h5:
            name: profiles_buttons_formatting_option_h5
            openWith:
                textile: "h5. "
        h6:
            name: profiles_buttons_formatting_option_h6
            openWith:
                textile: "h6. "
        p:
            name: profiles_buttons_formatting_option_p
            openWith:
                textile: "p. "

image:
    name: profiles_buttons_image
    className: image
    replaceWith:
        textile: "function(h) {return btnImageCallback(h);}"

italic:
    name: profiles_buttons_italic
    key: I
    className: italic
    closeWith:
        textile: "_"
    openWith:
        textile: "_"

link:
    name: profiles_buttons_link
    className: link
    children:
        internal:
            name: profiles_buttons_link_option_internal
            replaceWith:
                textile: "function(h) {return btnLinkInternalCallback(h);}"
        external:
            name: profiles_buttons_link_option_external
            replaceWith:
                textile: "function(h) {return btnLinkExternalCallback(h);}"
        mailto:
            name: profiles_buttons_link_option_mailto
            replaceWith:
                textile: "function(h) {return btnLinkMailtoCallback(h);}"

orderedlist:
    name: profiles_buttons_orderedlist
    className: orderedlist
    replaceWith:
        textile: "function(h) {return btnOrderedlistCallback(h);}"

quote:
    name: profiles_buttons_quote
    className: quote
    closeWith:
        textile: ""
    openWith:
        textile: "bq. "

sub:
    name: profiles_buttons_sub
    className: sub
    closeWith:
        textile: "~"
    openWith:
        textile: "~"

sup:
    name: profiles_buttons_sup
    className: sup
    closeWith:
        textile: "^"
    openWith:
        textile: "^"

table:
    name: profiles_buttons_table
    className: table
    replaceWith:
        textile: "function(h) {return btnTableCallback(h);}"

underline:
    name: profiles_buttons_underline
    key: U
    className: underline
    closeWith:
        textile: "+"
    openWith:
        textile: "+"

unorderedlist:
    name: profiles_buttons_unorderedlist
    className: unorderedlist
    replaceWith:
        textile: "function(h) {return btnUnorderedlistCallback(h);}"