package: rex_markitup
version: '1.3.2'
author: Thomas Kaegi
supportpage: github.com/phoebusryan/rex_markitup

page:
    title: 'translate:title'
    perm: rex_markitup[]
    pjax: true
    subpages:
        tutorial: { title: 'translate:tutorial', perm: rex_markitup[tutorial] }
        profiles: { title: 'translate:profiles', perm: rex_markitup[profiles] }