package: rex_markitup
version: '2.1.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/rex_markitup

page:
    title: 'translate:title'
    perm: rex_markitup[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: rex_markitup[profiles] }

conflicts:
    packages:
        textile: *
