package: markitup
version: '3.3.4'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/markitup

page:
    title: 'translate:title'
    perm: markitup[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: markitup[profiles] }
        snippets: { title: 'translate:snippets', perm: markitup[snippets] }

conflicts:
    packages:
        textile: '*'

requires:
    redaxo: '^5.1.0'
