package: rex_markitup
version: '1.4.2'
author: Thomas Kaegi
supportpage: github.com/phoebusryan/rex_markitup

page:
    title: 'translate:title'
    perm: rex_markitup[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: rex_markitup[profiles] }